package io.github.darrindeyoung791.habitpulse.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (Purple theme as seed)
val PurplePrimary = Color(0xFF6750A4)
val PurpleOnPrimary = Color(0xFFFFFFFF)
val PurplePrimaryContainer = Color(0xFFEADDFF)
val PurpleOnPrimaryContainer = Color(0xFF21005D)

val PurpleSecondary = Color(0xFF625B71)
val PurpleOnSecondary = Color(0xFFFFFFFF)
val PurpleSecondaryContainer = Color(0xFFE8DEF8)
val PurpleOnSecondaryContainer = Color(0xFF1D192B)

val PurpleTertiary = Color(0xFF7D5260)
val PurpleOnTertiary = Color(0xFFFFFFFF)
val PurpleTertiaryContainer = Color(0xFFFFD8E4)
val PurpleOnTertiaryContainer = Color(0xFF31111D)

val PurpleError = Color(0xFFB3261E)
val PurpleOnError = Color(0xFFFFFFFF)
val PurpleErrorContainer = Color(0xFFF9DEDC)
val PurpleOnErrorContainer = Color(0xFF410E0B)

val PurpleBackground = Color(0xFFFFFBFE)
val PurpleOnBackground = Color(0xFF1C1B1F)
val PurpleSurface = Color(0xFFFFFBFE)
val PurpleOnSurface = Color(0xFF1C1B1F)
val PurpleSurfaceVariant = Color(0xFFE7E0EC)
val PurpleOnSurfaceVariant = Color(0xFF49454F)
val PurpleOutline = Color(0xFF79747E)
val PurpleOutlineVariant = Color(0xFFCAC4D0)
val PurpleInverseSurface = Color(0xFF313033)
val PurpleInverseOnSurface = Color(0xFFF4EFF4)
val PurpleInversePrimary = Color(0xFFD0BCFF)
val PurpleSurfaceTint = Color(0xFF6750A4)

// Dark Theme Colors (Purple theme as seed)
val PurpleDarkPrimary = Color(0xFFD0BCFF)
val PurpleDarkOnPrimary = Color(0xFF381E72)
val PurpleDarkPrimaryContainer = Color(0xFF4F378B)
val PurpleDarkOnPrimaryContainer = Color(0xFFEADDFF)

val PurpleDarkSecondary = Color(0xFFCCC2DC)
val PurpleDarkOnSecondary = Color(0xFF332D41)
val PurpleDarkSecondaryContainer = Color(0xFF4A4458)
val PurpleDarkOnSecondaryContainer = Color(0xFFE8DEF8)

val PurpleDarkTertiary = Color(0xFFEFB8C8)
val PurpleDarkOnTertiary = Color(0xFF492532)
val PurpleDarkTertiaryContainer = Color(0xFF633B48)
val PurpleDarkOnTertiaryContainer = Color(0xFFFFD8E4)

val PurpleDarkError = Color(0xFFF2B8B5)
val PurpleDarkOnError = Color(0xFF601410)
val PurpleDarkErrorContainer = Color(0xFF8C1D18)
val PurpleDarkOnErrorContainer = Color(0xFFF9DEDC)

val PurpleDarkBackground = Color(0xFF1C1B1F)
val PurpleDarkOnBackground = Color(0xFFE6E1E5)
val PurpleDarkSurface = Color(0xFF1C1B1F)
val PurpleDarkOnSurface = Color(0xFFE6E1E5)
val PurpleDarkSurfaceVariant = Color(0xFF49454F)
val PurpleDarkOnSurfaceVariant = Color(0xFFCAC4D0)
val PurpleDarkOutline = Color(0xFF938F99)
val PurpleDarkOutlineVariant = Color(0xFF49454F)
val PurpleDarkInverseSurface = Color(0xFFE6E1E5)
val PurpleDarkInverseOnSurface = Color(0xFF313033)
val PurpleDarkInversePrimary = Color(0xFF6750A4)
val PurpleDarkSurfaceTint = Color(0xFFD0BCFF)